### ISSUE TITLE
ROADMAP_CANBAN_PRACTICA8

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-m#1]
[practica 8_Gestion_de_Proyectos.pdf](https://github.com/user-attachments/files/17498045/practica.8_Gestion_de_Proyectos.pdf)
https://github.com/SistemasTecTlaxiaco/webfood

**Comment by carlos0716c** [comment]
portada y los escudos institucionales: 25 puntos
Describe el procedimiento: 25 puntos
Incluye ilustraciones y capturas: 25 puntos
Conclusión: 25 puntos
Puntaje alcanzado 100% = 20 puntos

**Comment by josealfredo79** [comment]
bien hecho y revisado..
