### ISSUE TITLE
Practica10

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-m#2]
[PRACTICA10_GESTION_DE_PROYECTOS.pdf](https://github.com/user-attachments/files/18067514/PRACTICA10_GESTION_DE_PROYECTOS.pdf)

**Comment by isairey** [comment]
*Portada y los escudos* institucionales: 25 puntos
*Objetivos* de la práctica, bien desarrollados: 25 puntos
*Procedimiento* bien redactado y detallado: 25 puntos
Muestra *resultados y conclusiones* cumpliendo con los criterios establecidos: 20 puntos (faltaron resultados imágenes de las transacciones hechas)

Puntaje alcanzado 100% = 47.5 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
